<a href="https://colab.research.google.com/github/Burgunthy/Tensorflow2_Practice/blob/main/tf2-04-3-file_input_linear_regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf
import numpy as np

In [4]:
xy = np.loadtxt('./drive/My Drive/Colab Notebooks/tf2_practice/tf2_04_2_data.csv', delimiter=',', dtype=np.float32)       # 기존에 있는 csv 파일 사용
# filename_queue = tf.train.string_input_producer([], shuffle=False, name'')
# record_defaults = [[][][][]]
# xy = tf.decode_csv(value, record_defaults)
# if.train.batch([xy[], xy[]], batch_size=10)

# file을 여러개 사용한다면 queue 사용.

x_data = xy[:, 0:-1]
# 앞의 세 행만 불러온다
y_data = xy[:, [-1]]
# 마지막 항을 불러온다

print(x_data, "\nx_data shape:", x_data.shape)
print(y_data, "\ny_data shape:", y_data.shape)
# x와 y 데이터 shape와 수 확인 len(x_data)도 하면 좋다

[[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]
 [ 53.  46.  55.]] 
x_data shape: (6, 3)
[[152.]
 [185.]
 [180.]
 [196.]
 [142.]
 [101.]] 
y_data shape: (6, 1)


In [6]:
tf.model = tf.keras.Sequential()
# activation function doesn't have to be added as a separate layer. Add it as an argument of Dense() layer
tf.model.add(tf.keras.layers.Dense(units=1, input_dim=3, activation='linear'))
# 활성함수로 선형함수 사용

tf.model.summary()
# 여기는 왜 summary를 먼저 했을까? -> 다를 것이 없다. compile 이전에 원하는 곳에서 확인
tf.model.compile(loss='mse', optimizer=tf.keras.optimizers.SGD(lr=1e-5))
tf.model.summary()

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_2 (Dense)              (None, 1)                 4         
Total params: 4
Trainable params: 4
Non-trainable params: 0
_________________________________________________________________
Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_2 (Dense)              (None, 1)                 4         
Total params: 4
Trainable params: 4
Non-trainable params: 0
_________________________________________________________________


In [ ]:
tf.model.compile(loss='mse', optimizer=tf.keras.optimizers.SGD(lr=1e-5))
history = tf.model.fit(x_data, y_data, epochs=2000)
# model.fit(data, labels, batch_size=32, epochs=5) 위치 파악 필요

In [8]:
# Ask my score
print("Your score will be ", tf.model.predict([[100, 70, 101]]))
print("Other scores will be ", tf.model.predict([[60, 70, 110], [90, 100, 80]]))

Your score will be  [[173.03482]]
Other scores will be  [[192.31229]
 [177.24442]]
