<a href="https://colab.research.google.com/github/Burgunthy/Tensorflow2_Practice/blob/main/tf2-12-1-hello-rnn.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# hihello 입력 후 다음 문자 출력 함수 생성

import numpy as np
import tensorflow as tf

In [2]:
idx2char = ['h', 'i', 'e', 'l', 'o']
# Teach hello: hihell -> ihello
# x_data = [[0, 1, 0, 2, 3, 3]]  # hihell
y_data = [[1, 0, 2, 3, 3, 4]]  # ihello

num_classes = 5
input_dim = 5  # one-hot size, same as hidden_size to directly predict one-hot
sequence_length = 6  # |ihello| == 6
learning_rate = 0.1

x_one_hot = np.array([[[1, 0, 0, 0, 0],    # h 0
                       [0, 1, 0, 0, 0],    # i 1
                       [1, 0, 0, 0, 0],    # h 0
                       [0, 0, 1, 0, 0],    # e 2
                       [0, 0, 0, 1, 0],    # l 3
                       [0, 0, 0, 1, 0]]],  # l 3
                     dtype=np.float32)

y_one_hot = tf.keras.utils.to_categorical(y_data, num_classes=num_classes)
print(x_one_hot.shape)
print(y_one_hot.shape)

(1, 6, 5)
(1, 6, 5)


In [3]:
tf.model = tf.keras.Sequential()

# make cell and add it to RNN layer
# input_shape = (1,6,5) => number of sequence (batch), length of sequence, size of input dim
cell = tf.keras.layers.LSTMCell(units=num_classes, input_shape=(sequence_length, input_dim))
tf.model.add(tf.keras.layers.RNN(cell=cell, return_sequences=True))

# single LSTM layer can be used as well instead of creating LSTMCell
# tf.model.add(tf.keras.layers.LSTM(units=num_classes, input_shape=(sequence_length, input_dim), return_sequences=True))

# fully connected layer
tf.model.add(tf.keras.layers.TimeDistributed(tf.keras.layers.Dense(units=num_classes, activation='softmax')))

tf.model.compile(loss='categorical_crossentropy', optimizer=tf.keras.optimizers.Adam(lr=learning_rate),
                 metrics=['accuracy'])

# train
tf.model.fit(x_one_hot, y_one_hot, epochs=50)
tf.model.summary()

Epoch 1/50
1/1 [==============================] - 0s 2ms/step - loss: 1.5923 - accuracy: 0.1667
Epoch 2/50
1/1 [==============================] - 0s 2ms/step - loss: 1.4523 - accuracy: 0.3333
Epoch 3/50
1/1 [==============================] - 0s 5ms/step - loss: 1.3483 - accuracy: 0.3333
Epoch 4/50
1/1 [==============================] - 0s 2ms/step - loss: 1.2437 - accuracy: 0.3333
Epoch 5/50
1/1 [==============================] - 0s 2ms/step - loss: 1.1166 - accuracy: 0.5000
Epoch 6/50
1/1 [==============================] - 0s 2ms/step - loss: 0.9834 - accuracy: 0.6667
Epoch 7/50
1/1 [==============================] - 0s 5ms/step - loss: 0.8566 - accuracy: 0.6667
Epoch 8/50
1/1 [==============================] - 0s 2ms/step - loss: 0.7241 - accuracy: 1.0000
Epoch 9/50
1/1 [==============================] - 0s 2ms/step - loss: 0.5933 - accuracy: 1.0000
Epoch 10/50
1/1 [==============================] - 0s 5ms/step - loss: 0.4785 - accuracy: 1.0000
Epoch 11/50
1/1 [======================

In [4]:
predictions = tf.model.predict(x_one_hot)
for i, prediction in enumerate(predictions):
    print(prediction)
    # print char using argmax, dict
    result_str = [idx2char[c] for c in np.argmax(prediction, axis=1)]
    print("\tPrediction str: ", ''.join(result_str))

[[1.7770071e-03 9.9767619e-01 4.6780051e-04 4.4849673e-07 7.8629382e-05]
 [9.9736506e-01 1.2151562e-03 1.1800779e-03 2.3962966e-04 1.2974199e-07]
 [6.5184571e-04 1.0281116e-03 9.9824381e-01 7.1219103e-05 5.0844169e-06]
 [5.9377835e-05 2.0054846e-07 1.4559986e-04 9.9977762e-01 1.7153672e-05]
 [6.3100271e-07 1.1102338e-06 3.7617821e-04 9.9754971e-01 2.0723415e-03]
 [1.3128529e-09 2.0909474e-04 6.2762524e-07 7.9497532e-04 9.9899524e-01]]
	Prediction str:  ihello
