<a href="https://colab.research.google.com/github/Burgunthy/Tensorflow2_Practice/blob/main/tf2-06-1-softmax_classifier.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# softmax classifier

import tensorflow as tf
import numpy as np

In [2]:
x_raw = [[1, 2, 1, 1],
          [2, 1, 3, 2],
          [3, 1, 3, 4],
          [4, 1, 5, 5],
          [1, 7, 5, 5],
          [1, 2, 5, 6],
          [1, 6, 6, 6],
          [1, 7, 7, 7]]
y_raw = [[0, 0, 1],
          [0, 0, 1],
          [0, 0, 1],
          [0, 1, 0],
          [0, 1, 0],
          [0, 1, 0],
          [1, 0, 0],
          [1, 0, 0]]

x_data = np.array(x_raw, dtype=np.float32)
y_data = np.array(y_raw, dtype=np.float32)
# x_raw, y_raw를 float 형태로 변환

nb_classes = 3
# 선언도 괜찮지만 x_data.shape[1]과 같이 사용 가능

In [ ]:
tf.model = tf.keras.Sequential()
tf.model.add(tf.keras.layers.Dense(input_dim=4, units=nb_classes, use_bias=True))
# use_bias = True, 디폴트

# use softmax activations: softmax = exp(logits) / reduce_sum(exp(logits), dim)
tf.model.add(tf.keras.layers.Activation('softmax'))
# 결과값이 여러개로 이루어져 있으므로 softmax 사용

# use loss == categorical_crossentropy
tf.model.compile(loss='categorical_crossentropy', optimizer=tf.keras.optimizers.SGD(lr=0.1), metrics=['accuracy'])
# 해당 loss 이용 시 one hot encoding 필요
# sparse_categorical_crossentropy -> one hot encoding된 형태로 출력된다

tf.model.summary()

history = tf.model.fit(x_data, y_data, epochs=2000)

In [6]:
print('--------------')
# Testing & One-hot encoding
a = tf.model.predict(np.array([[1, 11, 7, 9]]))
print(a, tf.keras.backend.eval(tf.argmax(a, axis=1)))

print('--------------')
b = tf.model.predict(np.array([[1, 3, 4, 3]]))
print(b, tf.keras.backend.eval(tf.argmax(b, axis=1)))

print('--------------')
# or use argmax embedded method, predict_classes
c = tf.model.predict(np.array([[1, 1, 0, 1]]))
c_onehot = tf.model.predict_classes(np.array([[1, 1, 0, 1]]))
print(c, c_onehot)

print('--------------')
# 한번에도 사용 가능
all = tf.model.predict(np.array([[1, 11, 7, 9], [1, 3, 4, 3], [1, 1, 0, 1]]))
all_onehot = tf.model.predict_classes(np.array([[1, 11, 7, 9], [1, 3, 4, 3], [1, 1, 0, 1]]))
print(all, all_onehot)

--------------
[[3.2084093e-03 9.9678326e-01 8.2792212e-06]] [1]
--------------
[[0.88989997 0.10141009 0.00869003]] [0]
--------------
[[1.0453585e-08 3.1753207e-04 9.9968243e-01]] [2]
--------------
[[3.20840464e-03 9.96783257e-01 8.27921303e-06]
 [8.89899969e-01 1.01410106e-01 8.69003590e-03]
 [1.04535651e-08 3.17531783e-04 9.99682426e-01]] [1 0 2]
